***************
*** 4,28 ****
  #### Start of system configuration section. ####
  
  srcdir = .
- topdir = /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/universal-darwin10.0
  hdrdir = $(topdir)
  VPATH = $(srcdir):$(topdir):$(hdrdir)
  exec_prefix = $(prefix)
- prefix = $(DESTDIR)/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr
  sharedstatedir = $(prefix)/com
- mandir = $(DESTDIR)/usr/share/man
  psdir = $(docdir)
  oldincludedir = $(DESTDIR)/usr/include
  localedir = $(datarootdir)/locale
  bindir = $(exec_prefix)/bin
- libexecdir = $(exec_prefix)/libexec
- sitedir = $(DESTDIR)/Library/Ruby/Site
  htmldir = $(docdir)
  vendorarchdir = $(vendorlibdir)/$(sitearch)
  includedir = $(prefix)/include
- infodir = $(DESTDIR)/usr/share/info
  vendorlibdir = $(vendordir)/$(ruby_version)
- sysconfdir = $(prefix)/etc
  libdir = $(exec_prefix)/lib
  sbindir = $(exec_prefix)/sbin
  rubylibdir = $(libdir)/ruby/$(ruby_version)
--- 4,28 ----
  #### Start of system configuration section. ####
  
  srcdir = .
+ topdir = /usr/lib/ruby/1.8/i486-linux
  hdrdir = $(topdir)
  VPATH = $(srcdir):$(topdir):$(hdrdir)
  exec_prefix = $(prefix)
+ prefix = $(DESTDIR)/usr
  sharedstatedir = $(prefix)/com
+ mandir = $(prefix)/share/man
  psdir = $(docdir)
  oldincludedir = $(DESTDIR)/usr/include
  localedir = $(datarootdir)/locale
  bindir = $(exec_prefix)/bin
+ libexecdir = $(prefix)/lib/ruby1.8
+ sitedir = $(DESTDIR)/usr/local/lib/site_ruby
  htmldir = $(docdir)
  vendorarchdir = $(vendorlibdir)/$(sitearch)
  includedir = $(prefix)/include
+ infodir = $(prefix)/share/info
  vendorlibdir = $(vendordir)/$(ruby_version)
+ sysconfdir = $(DESTDIR)/etc
  libdir = $(exec_prefix)/lib
  sbindir = $(exec_prefix)/sbin
  rubylibdir = $(libdir)/ruby/$(ruby_version)
***************
*** 34,68 ****
  archdir = $(rubylibdir)/$(arch)
  sitearchdir = $(sitelibdir)/$(sitearch)
  datadir = $(datarootdir)
- localstatedir = $(prefix)/var
  sitelibdir = $(sitedir)/$(ruby_version)
  
  CC = gcc
  LIBRUBY = $(LIBRUBY_SO)
  LIBRUBY_A = lib$(RUBY_SO_NAME)-static.a
  LIBRUBYARG_SHARED = -l$(RUBY_SO_NAME)
- LIBRUBYARG_STATIC = -l$(RUBY_SO_NAME)
  
  RUBY_EXTCONF_H = 
- CFLAGS   =  -fno-common -arch i386 -arch x86_64 -g -Os -pipe -fno-common -DENABLE_DTRACE  -fno-common  -pipe -fno-common $(cflags) 
  INCFLAGS = -I. -I$(topdir) -I$(hdrdir) -I$(srcdir)
- DEFS     = 
- CPPFLAGS = -DHAVE_RUBY_H  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE $(DEFS) $(cppflags)
  CXXFLAGS = $(CFLAGS) 
- ldflags  = -L. -arch i386 -arch x86_64 
  dldflags = 
  archflag = 
  DLDFLAGS = $(ldflags) $(dldflags) $(archflag)
- LDSHARED = cc -arch i386 -arch x86_64 -pipe -bundle -undefined dynamic_lookup
  AR = ar
  EXEEXT = 
  
- RUBY_INSTALL_NAME = ruby
- RUBY_SO_NAME = ruby
- arch = universal-darwin10.0
- sitearch = universal-darwin10.0
  ruby_version = 1.8
- ruby = /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby
  RUBY = $(ruby)
  RM = rm -f
  MAKEDIRS = mkdir -p
--- 34,68 ----
  archdir = $(rubylibdir)/$(arch)
  sitearchdir = $(sitelibdir)/$(sitearch)
  datadir = $(datarootdir)
+ localstatedir = $(DESTDIR)/var
  sitelibdir = $(sitedir)/$(ruby_version)
  
  CC = gcc
  LIBRUBY = $(LIBRUBY_SO)
  LIBRUBY_A = lib$(RUBY_SO_NAME)-static.a
  LIBRUBYARG_SHARED = -l$(RUBY_SO_NAME)
+ LIBRUBYARG_STATIC = -l$(RUBY_SO_NAME)-static
  
  RUBY_EXTCONF_H = 
+ CFLAGS   =  -fPIC -fno-strict-aliasing -g -g -O2  -fPIC $(cflags) 
  INCFLAGS = -I. -I$(topdir) -I$(hdrdir) -I$(srcdir)
+ DEFS     = -D_FILE_OFFSET_BITS=64
+ CPPFLAGS = -DHAVE_RUBY_H  $(DEFS) $(cppflags)
  CXXFLAGS = $(CFLAGS) 
+ ldflags  = -L. -Wl,-Bsymbolic-functions -rdynamic -Wl,-export-dynamic
  dldflags = 
  archflag = 
  DLDFLAGS = $(ldflags) $(dldflags) $(archflag)
+ LDSHARED = $(CC) -shared
  AR = ar
  EXEEXT = 
  
+ RUBY_INSTALL_NAME = ruby1.8
+ RUBY_SO_NAME = ruby1.8
+ arch = i486-linux
+ sitearch = i486-linux
  ruby_version = 1.8
+ ruby = /usr/bin/ruby1.8
  RUBY = $(ruby)
  RM = rm -f
  MAKEDIRS = mkdir -p
***************
*** 86,96 ****
  extout_prefix = 
  target_prefix = 
  LOCAL_LIBS = 
- LIBS = $(LIBRUBYARG_SHARED)  -lpthread -ldl  
- SRCS = ext.c match.c matcher.c
- OBJS = ext.o match.o matcher.o
  TARGET = ext
- DLLIB = $(TARGET).bundle
  EXTSTATIC = 
  STATIC_LIB = 
  
--- 86,96 ----
  extout_prefix = 
  target_prefix = 
  LOCAL_LIBS = 
+ LIBS = $(LIBRUBYARG_SHARED)  -lpthread -lrt -ldl -lcrypt -lm   -lc
+ SRCS = match.c ext.c matcher.c
+ OBJS = match.o ext.o matcher.o
  TARGET = ext
+ DLLIB = $(TARGET).so
  EXTSTATIC = 
  STATIC_LIB = 
  
***************
*** 100,106 ****
  RUBYARCHDIR   = $(sitearchdir)$(target_prefix)
  
  TARGET_SO     = $(DLLIB)
- CLEANLIBS     = $(TARGET).bundle $(TARGET).il? $(TARGET).tds $(TARGET).map
  CLEANOBJS     = *.o *.a *.s[ol] *.pdb *.exp *.bak
  
  all:		$(DLLIB)
--- 100,106 ----
  RUBYARCHDIR   = $(sitearchdir)$(target_prefix)
  
  TARGET_SO     = $(DLLIB)
+ CLEANLIBS     = $(TARGET).so $(TARGET).il? $(TARGET).tds $(TARGET).map
  CLEANOBJS     = *.o *.a *.s[ol] *.pdb *.exp *.bak
  
  all:		$(DLLIB)
